# Generated by Django 5.2 on 2025-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('description_ar', models.TextField()),
                ('name_en', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('sectors', models.ManyToManyField(related_name='services', to='sectors.sector')),
            ],
        ),
    ]
