# Generated by Django 5.2 on 2025-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAccessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('linkname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StartYourFuture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ابدأ مستقبلك', editable=False, max_length=255)),
                ('subtitle', models.CharField(default='التقديم مفتوح الأن', editable=False, max_length=255)),
                ('description', models.TextField()),
                ('videourl', models.URLField()),
                ('url', models.URLField()),
                ('moredetails', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='احصائيات جامعة دمنهور', editable=False, max_length=255)),
                ('instructors', models.PositiveIntegerField()),
                ('students', models.PositiveIntegerField()),
                ('employees', models.PositiveIntegerField()),
                ('foreign_students', models.PositiveIntegerField()),
                ('programs', models.PositiveIntegerField()),
                ('colleges', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='university_info/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='university_info/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='university_info/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
