# Generated by Django 5.2 on 2025-04-17 23:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector_type', models.CharField(choices=[('main', 'القطاع الرئيسي'), ('units', 'الوحدات'), ('centers', 'المراكز'), ('sector', 'القطاع الفرعي')], default='main', max_length=10, verbose_name='نوع القطاع')),
                ('name_ar', models.CharField(max_length=255, unique=True, verbose_name='الاسم بالعربية')),
                ('description_ar', models.TextField(blank=True, max_length=1000, null=True, verbose_name='الوصف بالعربية')),
                ('message_ar', models.TextField(blank=True, max_length=500, null=True, verbose_name='رسالة القطاع بالعربية')),
                ('speech_ar', models.TextField(blank=True, max_length=1000, null=True, verbose_name='كلمة رئيس القطاع بالعربية')),
                ('name_en', models.CharField(max_length=255, unique=True, verbose_name='الاسم بالإنجليزية')),
                ('description_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='الوصف بالإنجليزية')),
                ('message_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='رسالة القطاع بالإنجليزية')),
                ('speech_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='كلمة رئيس القطاع بالإنجليزية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sectors/%Y/%m/%d/', verbose_name='صورة القطاع الرئيسية')),
                ('organizational_structure', models.ImageField(blank=True, help_text='رفع صورة الهيكل التنظيمي للقطاع', null=True, upload_to='sectors/structures/%Y/%m/%d/', verbose_name='الهيكل التنظيمي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قطاع',
                'verbose_name_plural': 'القطاعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
